crm/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from leads.views import HomePageView, RegisterView 
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name="homepage"),
    path('leads/', include('leads.urls', namespace="leads")),
    path('agents/', include('agents.urls', namespace="agents")),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="register"),
    path('password-reset/', PasswordResetView.as_view(), name="password_reset"),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from .views import (LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, 
                    LeadDeleteView, AssignAgentView, CategoryListView, CategoryDetailView, 
                    LeadCategoryUpdateView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView )


app_name = "leads"

urlpatterns = [
    path('', LeadListView.as_view(), name="lead-list"),
    path('<int:pk>/', LeadDetailView.as_view(), name="lead-detail"),
    path('create/', LeadCreateView.as_view(), name="lead-create"),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name="lead-update"),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name="lead-delete"),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name="assign-agent"),
    path('<int:pk>/category/', LeadCategoryUpdateView.as_view(), name="lead-category-update"),
    path('categories/', CategoryListView.as_view(), name="category-list"),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name="category-detail"),
    path('category-create/', CategoryCreateView.as_view(), name="category-create"),
    path('categories/<int:pk>/update', CategoryUpdateView.as_view(), name="category-update"),
    path('categories/<int:pk>/delete', CategoryDeleteView.as_view(), name="category-delete"),
]

leads/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    is_organisor = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey("Agent", null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey("Category", related_name="leads", null=True, blank=True, on_delete=models.SET_NULL)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()


    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email
    
class Category(models.Model):
    name = models.CharField(max_length=30)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user = instance)

post_save.connect(post_user_created_signal, sender=User)

leads/forms.py
from django import forms
from .models import Lead, Agent, Category
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = [
            'first_name','last_name', 'age', 'email','agent','description','phone_number',
        ]
        widgets = {
            'description': forms.Textarea(attrs={'rows': 1, 'cols': 30}),  # Adjust rows and cols as needed
        }

User = get_user_model()

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username'
        ]
        
class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organisation = request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents

class LeadCategoryForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = [
            'category',
        ]

class CategoryModelForm(forms.ModelForm):
    class Meta:
        model= Category
        fields=[
            'name'
        ]

leads/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect, reverse
from .models import Lead, Category
from django.views import generic
from .forms import LeadModelForm, CustomUserCreationForm, AssignAgentForm, LeadCategoryForm, CategoryModelForm
from django.contrib.auth.mixins import LoginRequiredMixin
from agents.mixins import OrganisorAndLoginRequiredMixin
from django.conf import settings

class RegisterView(generic.CreateView):
    template_name = 'registration/register.html'
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")

class HomePageView(generic.TemplateView):
    template_name = 'homepage.html'


class LeadListView(LoginRequiredMixin, generic.ListView):
    template_name = 'leads/lead_list.html'
    context_object_name = 'leads'

    # Assigned Leads to a specific agent
    def get_queryset(self):
        user = self.request.user
        # filter to show all leads the organisation have
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation = user.userprofile, agent__isnull = False)
        else:
            # filter to first access the agents org and 
            # then check a specific leads assigned to that agent
            queryset = Lead.objects.filter(organisation = user.agent.organisation, agent__isnull = False)
            queryset = Lead.objects.filter(agent__user = user)
        return queryset
    
    # Unassigned Leads
    def get_context_data(self, **kwargs):
        context = super(LeadListView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation = user.userprofile, agent__isnull = True)
            context.update({
                'unassigned_leads': queryset
            })
        return context


class LeadDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'leads/lead_detail.html'
    context_object_name = 'lead'

    def get_queryset(self):
        user = self.request.user
        # filter to show all leads the organisation have
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation = user.userprofile)
        else:
            # filter to first access the agents org and 
            # then check a specific leads assigned to that agent
            queryset = Lead.objects.filter(organisation = user.agent.organisation)
            queryset = Lead.objects.filter(agent__user = user)
        return queryset
    

class LeadCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    template_name = 'leads/lead_create.html'
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse("leads:lead-list")
    
    def form_valid(self, form):
        lead = form.save(commit=False)
        lead.organisation = self.request.user.userprofile
        lead.save()
        if lead.agent and lead.agent.user and lead.agent.user.email:
            send_mail(
                subject = "You've been assigned to the new lead.",
                message = "Visit the site to know more",
                from_email =settings.DEFAULT_FROM_EMAIL,
                recipient_list = [lead.agent.user.email]
            )
        return super(LeadCreateView, self).form_valid(form)                                                         

class LeadUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    template_name = 'leads/lead_update.html'
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse("leads:lead-list")
    
    def get_queryset(self):
        user = self.request.user
        # filter to show all leads the organisation have      
        return Lead.objects.filter(organisation = user.userprofile)
        

class LeadDeleteView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    template_name = 'leads/lead_delete.html'

    def get_success_url(self):
        return reverse("leads:lead-list")
    
    def get_queryset(self):
        user = self.request.user
        # filter to show all leads the organisation have      
        return Lead.objects.filter(organisation = user.userprofile)

class AssignAgentView(OrganisorAndLoginRequiredMixin, generic.FormView):
    template_name = 'leads/assign_agent.html'
    form_class = AssignAgentForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs(**kwargs)
        kwargs.update({
            "request": self.request
        })
        return kwargs

    def get_success_url(self):
        return reverse("leads:lead-list")
    
    def form_valid(self, form):
        agent = form.cleaned_data["agent"]
        lead = Lead.objects.get(id=self.kwargs["pk"])
        lead.agent = agent
        lead.save()
        if lead.agent and lead.agent.user and lead.agent.user.email:
            send_mail(
                subject = "You've been assigned to the new lead.",
                message = "Visit the site to know more",
                from_email =settings.DEFAULT_FROM_EMAIL,
                recipient_list = [lead.agent.user.email]
            )
        return super(AssignAgentView, self).form_valid(form)  
    

class CategoryListView(LoginRequiredMixin, generic.ListView):
    template_name = 'leads/category_list.html'
    context_object_name = 'category_list'

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        user = self.request.user
        # unassgined_leads count
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation = user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation = user.agent.organisation)
        
        context.update({
                "fresh_lead_count": queryset.filter(category__isnull=True).count(),
                
        })
        return context

    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Category.objects.filter(organisation = user.userprofile)
        else:
            queryset = Category.objects.filter(organisation = user.agent.organisation)
        return queryset
    

class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    template_name= 'leads/category_detail.html'
    context_object_name = 'category'

    def get_context_data(self, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(**kwargs)
        leads = self.get_object().leads.all()

        context.update({
                "leads": leads
        })
        return context

    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Category.objects.filter(organisation = user.userprofile)
        else:
            queryset = Category.objects.filter(organisation = user.agent.organisation)
        return queryset
    
class LeadCategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'leads/lead_category_update.html'
    form_class = LeadCategoryForm

    def get_success_url(self):
        return reverse("leads:lead-detail", kwargs={"pk": self.get_object().id})
    
    def get_queryset(self):
        user = self.request.user
        # filter to show all leads the organisation have
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation = user.userprofile)
        else:
            # filter to first access the agents org and 
            # then check a specific leads assigned to that agent
            queryset = Lead.objects.filter(organisation = user.agent.organisation)
            queryset = Lead.objects.filter(agent__user = user)
        return queryset

class CategoryCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    template_name = 'leads/category_create.html'
    context_object_name = 'category'
    form_class = CategoryModelForm

    def get_success_url(self):
        return reverse("leads:category-list")
    
    def form_valid(self, form):
        category = form.save(commit=False)
        category.organisation = self.request.user.userprofile
        category.save()
        return super(CategoryCreateView, self).form_valid(form)
    
class CategoryUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    template_name = 'leads/category_update.html'
    form_class = CategoryModelForm

    def get_success_url(self):
        return reverse("leads:category-list")
         
    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Category.objects.filter(organisation = user.userprofile)
        else:
            queryset = Category.objects.filter(organisation = user.agent.organisation)
        return queryset
    
class CategoryDeleteView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    template_name = 'leads/category_delete.html'

    def get_success_url(self):
        return reverse("leads:category-list")
    
    def get_queryset(self):
        user = self.request.user
        if user.is_organisor:
            queryset = Category.objects.filter(organisation = user.userprofile)
        else:
            queryset = Category.objects.filter(organisation = user.agent.organisation)
        return queryset
    

leads/templates/leads/assign_agent.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container py-5">
    <div class="row mb-4">
        <div class="col-md-8">
            <a href="{% url 'leads:lead-list' %}" class="btn btn-outline-dark mb-3">
                <i class="bi bi-arrow-left me-2"></i>Back to leads list
            </a>
            <h1 class="display-4">Assign an agent to this lead</h1>
        </div>
    </div>

    <div class="card shadow-sm rounded">
        <div class="card-body rounded">
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-dark mt-3">Assign</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

leads/templates/leads/category_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="container py-5">
        <div class="row mb-4">
            <div class="col-md-8">
                <a href="{% url 'leads:category-list' %}" class="btn btn-outline-dark mb-3">
                    <i class="bi bi-arrow-left me-2"></i>Back to categories list
                </a>
                <h1 class="display-4">Create a New Category</h1>
            </div>
        </div>

        <div class="card shadow-sm rounded">
            <div class="card-body rounded">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-dark mt-3">Create</button>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

leads/templates/leads/category_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container py-5">
    <div class="row mb-4">
        <div class="col-md-8">
            <a href="{% url 'leads:category-detail' category.pk %}" class="btn btn-outline-dark mb-3">
                <i class="bi bi-arrow-left me-2"></i>Back to {{ category.name }} Leads
            </a>
            <h1 class="display-4">Delete {{ category.name }}</h1>
        </div>
    </div>

    <div class="card shadow-sm rounded">
        <div class="card-body rounded">
            <p class="lead mb-4">Are you sure you want to delete the category "{{ category.name }}"?</p>
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="mt-3">
                    <button type="submit" class="btn btn-danger">Delete</button>
                    <a href="{% url 'leads:category-detail' category.pk %}" class="btn btn-outline-secondary ms-2">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

leads/templates/leads/category_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<main class="flex-grow-1">
    <section class="py-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <a href="{% url 'leads:category-list' %}" class="btn btn-outline-dark mb-3">
                        <i class="bi bi-arrow-left me-2"></i>Back to categories list
                    </a>
                    <div class="text-center mb-4">
                        <h1 class="mb-3">{{ category.name }} Leads</h1>
                        <div class="d-flex justify-content-center gap-2">
                            <a href="{% url 'leads:category-update' category.pk %}" class="btn btn-dark">
                                <i class="bi bi-pencil-square me-2"></i>Update category
                            </a>
                            <a href="{% url 'leads:category-delete' category.pk %}" class="btn btn-danger">
                                <i class="bi bi-trash me-2"></i>Delete category
                            </a>
                        </div>
                    </div>
                    <div class="card lead-table shadow-sm rounded">
                        <div class="card-body rounded">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th class="rounded-start" scope="col">Name</th>
                                        <th class="col-md-6 rounded-end" scope="col">Agent assigned</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for lead in category.leads.all %}
                                        <tr>
                                            <td class="custom-hover">
                                                <a class="text-decoration-none text-reset" href="{% url 'leads:lead-detail' lead.pk %}">{{ lead.first_name }} {{ lead.last_name }}</a>
                                            </td>
                                            <td>{{ lead.agent.user.email }}</td>
                                        </tr>
                                    {% endfor %}   
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock content %}

leads/templates/leads/category_list.html
{% extends "base.html" %}
{% block content %}

    <main class="flex-grow-1">
        <section class="py-5">
            <div class="container">
                <div class="text-center mb-4">
                    <h1 class="mb-3">Lead Categories</h1>
                        {% if user.is_organisor %}
                            <a href="{% url 'leads:category-create' %}" class="btn btn-dark">
                            <i class="bi bi-plus-circle me-2"></i>Create new category
                        {% endif %}
                    </a>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <div class="card lead-table shadow-sm rounded">
                            <div class="card-body rounded">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th class="rounded-start" scope="col">Category</th>
                                            <th class="col-md-6 rounded-end" scope="col">Lead Count</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>Fresh</td>
                                            <td>{{ fresh_lead_count }}</td>
                                        </tr>
                                        {% if category_list %}
                                            {% for category in category_list %}
                                                <tr>
                                                    <td>
                                                        <a class="text-decoration-none text-reset" href="{% url 'leads:category-detail' category.pk %}">{{ category.name }}</a>
                                                    </td>
                                                    <td>{{ category.leads.count }}</td>
                                                </tr>
                                            {% endfor %}
                                        {% else %}
                                            <tr>
                                                <td colspan="2">No categories available.</td>
                                            </tr>
                                        {% endif %}     
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock content %}

leads/templates/leads/category_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="container py-5">
        <div class="row mb-4">
            <div class="col-md-8">
                <a href="{% url 'leads:category-detail' category.pk %}" class="btn btn-outline-dark mb-3">
                    <i class="bi bi-arrow-left me-2"></i>Back to {{ category.name }} Leads
                </a>
                <h1 class="display-4">Update {{ category.name }}</h1>
            </div>
        </div>

        <div class="card shadow-sm rounded">
            <div class="card-body rounded">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-dark mt-3">Create</button>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

leads/templates/leads/lead_category_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container py-5">
    <div class="row mb-4">
        <div class="col-md-8">
            <a href="{% url 'leads:lead-detail' lead.pk %}" class="btn btn-outline-dark mb-3">
                <i class="bi bi-arrow-left me-2"></i>Back to {{ lead.first_name }} {{ lead.last_name }}
            </a>
            <h1 class="display-4">Assign Category</h1>
        </div>
    </div>

    <div class="card shadow-sm">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-dark mt-3">Submit</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends "base.html" %}
{% block content %}

<div class="container py-5">
    <div class="row mb-4">
        <div class="col-md-8">
            <a href="{% url 'leads:lead-list' %}" class="btn btn-outline-dark mb-3">
                <i class="bi bi-arrow-left me-2"></i>Back to leads
            </a>
            <h1 class="display-4 mb-3">{{ lead.first_name }} {{ lead.last_name }}</h1>

        </div>

    </div>

    <div class="card shadow-sm rounded">
        <div class="card-body rounded">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h2 class="h3 mb-0">Overview</h2>
                <a href="{% url 'leads:lead-category-update' lead.pk %}" class="btn btn-dark">
                    <i class="bi bi-bookmark-plus-fill"></i> Change Category</a>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-6 mb-3">
                    <h5 class="text-black">Description</h5>
                    <p class="lead">{{ lead.description }}</p>
                </div>
                <div class="col-md-6 mb-3">
                    <h5 class="text-black">Age</h5>
                    <p class="lead">{{ lead.age }}</p>
                </div>
                <div class="col-md-6 mb-3">
                    <h5 class="text-black">Email</h5>
                    <p class="lead">{{ lead.email }}</p>
                </div>
                <div class="col-md-6 mb-3">
                    <h5 class="text-black">Phone Number</h5>
                    <p class="lead">{{ lead.phone_number }}</p>
                </div>
                <div class="col-md-6 mb-3">
                    <h5 class="text-black">Agent Assigned</h5>
                    <p class="lead">{{ lead.agent }}</p>
                </div>
            </div>

            {% if request.user.is_organisor %}
            <div class="mt-4">
                <a href="{% url 'leads:lead-update' lead.pk %}" class="btn btn-dark me-2">Update Lead</a>
                <a href="{% url 'leads:lead-delete' lead.pk %}" class="btn btn-outline-danger">Delete Lead</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

leads/templates/leads/lead_list.html
{% extends "base.html" %}
{% block content %}

<div class="container py-5">
    <div class="row mb-4">
        <div class="col-md-8">
            <h2 class="display-4 mb-3">Leads({{ leads.count }})</h2>
            <a href="{% url 'leads:category-list' %}" class="text-decoration-none text-muted hover-primary">
                View categories
            </a>
        </div>
        {% if request.user.is_organisor %}
        <div class="col-md-4 text-md-end mt-5">
            <a href="{% url 'leads:lead-create' %}" class="btn btn-dark rounded">
                <i class="bi bi-plus-circle me-2"></i>Create a new lead
            </a>
        </div>
        {% endif %}
    </div>
    <hr>
    <div class="card shadow-sm rounded">
        <div class="card-body rounded">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead class="lead-table">
                        <tr>
                            <th class="rounded-start">Name</th>
                            <th>Email</th>
                            <th>Age</th>
                            <th>Phone Number</th>
                            <th>Category</th>
                            {% if user.is_organisor %}
                                <th class="rounded-end">Edit</th>
                            {% endif %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for lead in leads %}
                        <tr>
                            <td>
                                <a href="{% url 'leads:lead-detail' lead.pk %}" class="text-decoration-none fw-bold hover-primary text-black">{{ lead.first_name }} {{ lead.last_name }}</a>
                            </td>
                            <td>{{ lead.email }}</td>
                            <td>{{ lead.age }}</td>
                            <td>{{ lead.phone_number }}</td>
                            <td>
                                {% if lead.category %}
                                    <span class="badge bg-success rounded">{{ lead.category.name }}</span>
                                {% else %}
                                    <span class="badge bg-secondary rounded">Fresh</span>
                                {% endif %}
                            </td>
                            {% if user.is_organisor %}
                                <td>
                                    <a href="{% url 'leads:lead-update' lead.pk %}" class="btn btn-sm btn-outline-dark rounded">
                                        <i class="bi bi-pencil"></i>
                                    </a>
                                </td>
                            {% endif %}
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="7" class="text-center py-4">
                                <p class="text-muted mb-0">There are currently no leads</p>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    {% if unassigned_leads.exists %}
    <div class="mt-5">
        <h2 class="display-6 mb-4">Unassigned Leads({{ unassigned_leads.count }})</h2>
        <hr>
        <div class="row g-4">
            {% for lead in unassigned_leads %}
            <div class="col-md-6">
                <div class="card h-100 shadow-sm rounded">
                    <div class="card-body rounded">
                        <div class="d-flex align-items-center mb-3">
                            <div class="bg-primary text-white rounded-circle d-flex justify-content-center align-items-center p-4 me-3" style="width: 60px; height: 60px;">
                                <i class="bi bi-graph-up fs-3"></i>
                            </div>
                            <h3 class="card-title mb-0">{{ lead.first_name }} {{ lead.last_name }}</h3>
                        </div>
                        <p class="card-text p-1">{{ lead.description|truncatewords:20 }}</p>
                        <a href="{% url 'leads:assign-agent' lead.pk %}" class="btn btn-outline-dark rounded">
                            <i class="bi bi-person-check me-2"></i>Assign an agent
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
</div>

{% endblock content %}